<?php
//000000007000a:7:{i:0;a:7:{s:2:"id";s:3:"121";s:5:"title";s:77:"Alternative convertion between Greenco and Elmo Rietschle side channel blower";s:6:"author";s:30:"浙江格凌实业有限公司";s:7:"content";s:253:"Zhejiang Greenco Industry Co Ltd is a professional manufacturer of side channel blower (Seitenkanalverdichter) in China more than 13 years,.There are more than 300 different types and 10 series,Everyday we are producing 600pcs to 700pcs side channel ...";s:4:"time";s:10:"2013-08-25";s:4:"type";s:7:"support";s:3:"lan";s:5:"en-us";}i:1;a:7:{s:2:"id";s:3:"122";s:5:"title";s:30:"What are side channel blowers?";s:6:"author";s:30:"浙江格凌实业有限公司";s:7:"content";s:253:"side channel blowers are machines used to move air by way of a non-positive displacement method. A positive displacement device would trap a quantity of air and force it to move a given distance in a given direction. The method by which side channel ...";s:4:"time";s:10:"2013-08-06";s:4:"type";s:7:"support";s:3:"lan";s:5:"en-us";}i:2;a:7:{s:2:"id";s:3:"123";s:5:"title";s:40:"Side channel blower Operating Principle ";s:6:"author";s:30:"浙江格凌实业有限公司";s:7:"content";s:253:"The impellers in the G_series machines are mounted directly on the motor shaft for noncontact compression entirely without friction.Maximum operational reliability,even at high differential pressures.is ensured by the arrangement of the bearings outs...";s:4:"time";s:10:"2013-08-21";s:4:"type";s:7:"support";s:3:"lan";s:5:"en-us";}i:3;a:7:{s:2:"id";s:3:"124";s:5:"title";s:30:"Regenerative blower advantages";s:6:"author";s:30:"浙江格凌实业有限公司";s:7:"content";s:253:"Low noise level
The side channel blowers are equipped with built-in silencers.
The carrier plate is also silencing. A maximum degree
of noise reduction is achieved. The noise level during operation
is only 55 dB to 80 dB, depending on the model.
No v...";s:4:"time";s:10:"2013-08-12";s:4:"type";s:7:"support";s:3:"lan";s:5:"en-us";}i:4;a:7:{s:2:"id";s:3:"126";s:5:"title";s:35:"How to select a correct ring blower";s:6:"author";s:30:"浙江格凌实业有限公司";s:7:"content";s:253:"Here are some questions to consider regarding ring blower selection.Thinking about these issues will "jump start" the selection process. You might also write down your answers before you talk to us.
For pressure or vacuum application? 
Continuous or ...";s:4:"time";s:10:"2013-08-26";s:4:"type";s:7:"support";s:3:"lan";s:5:"en-us";}i:5;a:7:{s:2:"id";s:3:"127";s:5:"title";s:69:"Replacement of Taiwanese and Korean Ring blower by Greenco 2RB series";s:6:"author";s:30:"浙江格凌实业有限公司";s:7:"content";s:253:"Zhejiang Greenco Industry Co Ltd producing wide range of ring blower more than 300
different types,It has became the largest manufacturer all over the world.Our types even
more than Elmo Rietschle.Our Ring blower can be replaced previous manufacturer...";s:4:"time";s:10:"2013-08-27";s:4:"type";s:7:"support";s:3:"lan";s:5:"en-us";}i:6;a:7:{s:2:"id";s:3:"131";s:5:"title";s:60:"Mainternance and servicing of 2RB series regenerative blower";s:6:"author";s:30:"浙江格凌实业有限公司";s:7:"content";s:253:"Greenco 2RB series regenerative blower mainternance manual
		       1. Before start operating the regenerative blower
		       (1).Make sure that you had read the operating manual and understand the contents very well..
               (2).make sure b...";s:4:"time";s:10:"2013-09-01";s:4:"type";s:7:"support";s:3:"lan";s:5:"en-us";}}
?>